apiVersion: v1
kind: Pod
metadata:
  name: multus-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "host-device-capture-conf",
          "interface": "capture0"
        }
      ]

spec:
  # Let's add a nodeSelector - this will ensure the pod is scheduled on node1.
  nodeSelector:
    kubernetes.io/hostname: node1

  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash", "-c", "while true; do sleep 3600; done;"]
    # workaround for capture interface being DOWN inside the pod.
    securityContext:
      capabilities:
        add:
          - "NET_ADMIN"