# Here we provide a custom ConfigMap to define a couple of files
# that our Pod can use instead of the defaults.
apiVersion: v1
kind: ConfigMap
metadata:
  name: suricata-config
data:
  # minimal suricata.yaml for demo
  suricata.yaml: |
    %YAML 1.1
    ---
    vars:
      address-groups:
        HOME_NET: "[192.168.0.0/16]"
    outputs:
      - fast:
          enabled: yes
          filename: fast.log
          append: yes
    default-rule-path: /usr/local/etc/suricata/rules/
    rule-files:
      - local.rules

  # custom rule that we can trigger easily
  local.rules: |
    alert http $HOME_NET any -> $HOME_NET any (msg:"ET MALWARE bsides talk 1"; flow:established,to_server; http.method; content:"GET"; http.uri; content:"/bsides/badstuff.exe"; startswith; fast_pattern; sid:900001; rev:1;)

---

apiVersion: v1
kind: Pod
metadata:
  name: suricata-pod-2
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "host-device-capture-conf",
          "interface": "capture0"
        }
      ]
spec:
  nodeSelector:
    kubernetes.io/hostname: node1
  
  # Our new volume mount - the config map.
  volumes:
  - name: my-custom-config
    configMap:
      name: suricata-config
      items:
      - key: suricata.yaml
        path: suricata.yaml
  - name: my-custom-rules
    configMap:
      name: suricata-config
      items:
      - key: local.rules
        path: local.rules

  # Workaround for capture interface being DOWN inside the pod and suricata folder permissions.
  initContainers:
  - name: init-capture
    image: busybox
    command: ["/bin/sh", "-c", "ip link set capture0 up"]
    securityContext:
      capabilities:
        add:
          - "NET_ADMIN"
  
  containers:
  - name: suricata
    image: jasonish/suricata:6.0.9
    # Note we override the default configuration file.
    args: ["-c", "/usr/local/etc/suricata/suricata.yaml", "-i", "capture0"]
    securityContext:
      capabilities:
        add:
          - "NET_ADMIN"
          - "NET_RAW"
          - "SYS_NICE"

    # In addition to specifying the volume, we also need to mount it
    # into the Suricata container.
    volumeMounts:
    - name: my-custom-config
      mountPath: /usr/local/etc/suricata/
    - name: my-custom-rules
      mountPath: /usr/local/etc/suricata/rules/
